In [ ]:
Functional style programming - Single line code

In [1]:
def f1(a):
    return a+100

L = []

for var in [10,20,30,40]:
    r = f1(var)
    L.append(r)
    
print(L)

[110, 120, 130, 140]

In [2]:
list(map(lambda a:a+100,[10,20,30,40]))

[110, 120, 130, 140]

In [ ]:
  (1)         (2)
iterator ->generator 
list comprehension ->(3)
lambda ->(4)
map  ->(5)
filter ->(6)
reduce,enumerate ->(7)
---------
|
|->Functional style programming

In [ ]:
iterator - address 

In [8]:
print(hex(id(10)))

a = 10
b = 4+6
c = 5+5
d = 6+4
print(hex(id(a)),hex(id(b)),hex(id(c)),hex(id(d)))

0x7ffb5cef9448
0x7ffb5cef9448 0x7ffb5cef9448 0x7ffb5cef9448 0x7ffb5cef9448


In [12]:
s='abcab'    #   s|  a |  b  | c  | a |  b  |
             #    | 0  |  1  | 2  | 3 |  4  |<== index
             #      0x1            0x1
             #    [                           ] 0x12234 <---
            
print(s[0],hex(id(s[0])))
print(s[1],hex(id(s[1])))
print(s[3],hex(id(s[3])))
print('')
print(iter(s))

a 0x7ffb5cf04700
b 0x7ffb5cf04738
a 0x7ffb5cf04700



In [ ]:
To open this address(iterator)
  -> next(<iterator>) ...StopIterator
  -> for loop    
  |
  -> typecast to list   -> list(<iterator>) # python3.x

In [17]:
sobj = iter(s)
print(next(sobj))
print(next(sobj))
print(next(sobj))
print(next(sobj))
print(next(sobj))
print(next(sobj))

a
b
c
a
b


StopIteration: 

In [18]:
sobj = iter(s)
for var in sobj:
    print(var)

a
b
c
a
b


In [19]:
sobj = iter(s)
list(sobj)

['a', 'b', 'c', 'a', 'b']

In [22]:
fobj = open('E:\\emp.csv')
for var in fobj:
    print(var.strip())

eid,ename,edept,eplace,ecost
101,raj,sales,pune,1000
102,leo,prod,bglore,2000
103,paul,HR,chennai,3000
104,anu,hr,hyderabad,4000
456,kumar,sales,bglore,3000
105,zion,Hr,mumbai,5000
106,bibu,sales,bglore,1450
107,theeb,sales,noida,4590
108,bibu,sales,bglore,5000
113,kumar,prod,hyderabad,5423


In [23]:
for var in open('E:\\emp.csv'):
    print(var.strip())

eid,ename,edept,eplace,ecost
101,raj,sales,pune,1000
102,leo,prod,bglore,2000
103,paul,HR,chennai,3000
104,anu,hr,hyderabad,4000
456,kumar,sales,bglore,3000
105,zion,Hr,mumbai,5000
106,bibu,sales,bglore,1450
107,theeb,sales,noida,4590
108,bibu,sales,bglore,5000
113,kumar,prod,hyderabad,5423


In [25]:
fobj = open('E:\\emp.csv')
print(next(fobj))
print(next(fobj))

eid,ename,edept,eplace,ecost

101,raj,sales,pune,1000



In [ ]:
Generator 
  |->is a function ->returns an iterator(address)
                        ---> yield <value> 
                                Vs
                        ---> return <value>

In [26]:
def f1():
    return 10

def f2():
    yield 10
    
print(type(f1),type(f2))
print(type(f1()),type(f2()))

<class 'function'> <class 'function'>
<class 'int'> <class 'generator'>


In [28]:
fobj = f2()
print(next(fobj))
print(next(fobj))

10


StopIteration: 

In [29]:
def f1():
    return 10
    print("OK-1")
    print("OK-2")
    
def f2():
    yield 10
    print("Hello-1")
    print("Hello-2")
    yield 20,30
    yield "D1",["D2","D3"],["D4","D5"]
    
f1()

10

In [31]:
fobj = f2()

In [32]:
for var in fobj:
    print(var)

10
Hello-1
Hello-2
(20, 30)
('D1', ['D2', 'D3'], ['D4', 'D5'])


In [ ]:
list comprehension - list append operation
        |
     [final_value for iterable]
                    ---(1)->--
      ---<--(2)------------

In [33]:
L = []
for var in [10,20,30,40]:
    r = var+100
    L.append(r)
    
print(L)

[110, 120, 130, 140]


In [34]:
[var+100 for var in [10,20,30,40]]

[110, 120, 130, 140]

In [35]:
L = []
for var in [10,20,30,40]:
    if(var >20):
        r = var+100
        L.append(r)
    else:
        r = var+500
        L.append(r)
    
print(L)

[510, 520, 130, 140]


In [36]:
[var+100 if var>20 else var +500 for var in [10,20,30,40]]

[510, 520, 130, 140]

In [ ]:
# lambda - python keyword
  |-> unnamed function 
  |--> function call with args and return some value (Note: its not a generator)
  |--> lambda <list of args>:<basic operation>

In [37]:
def fx(a1,a2):
    return a1+a2

fx(10,20)

30

In [38]:
lambda a1,a2:a1+a2

<function __main__.<lambda>(a1, a2)>

In [39]:
fy = lambda a1,a2:a1+a2
fy(10,20)

30

In [42]:
f1 = lambda a1:a1>100
f1(120)
f1(50)

False

In [43]:
def f2(n):
    if(n >100):
        return n+100
    elif(n <100):
        return n+500

In [44]:
f3 = lambda a:f2(a)
f3(150)

250

In [ ]:
map(function,collection) -> <Generator>
|   ^^^^^^^^ __________
filter(function,collection) -><Generator>
       ^^^^^^^^ __________

In [40]:
def f1(a):
    return a+100

L = []

for var in [10,20,30,40]:
    r = f1(var)
    L.append(r)
    
print(L)

[110, 120, 130, 140]


In [46]:
obj = map(lambda a:a+100,[10,20,30,40])
for var in obj:
    print(var)

110
120
130
140


In [47]:
list(map(lambda a:a+100,[10,20,30,40]))

[110, 120, 130, 140]

In [56]:
fx = lambda a:a.read()
fx(open('E:\\emp.csv'))


'eid,ename,edept,eplace,ecost\n101,raj,sales,pune,1000\n102,leo,prod,bglore,2000\n103,paul,HR,chennai,3000\n104,anu,hr,hyderabad,4000\n456,kumar,sales,bglore,3000\n105,zion,Hr,mumbai,5000\n106,bibu,sales,bglore,1450\n107,theeb,sales,noida,4590\n108,bibu,sales,bglore,5000\n113,kumar,prod,hyderabad,5423'

In [ ]:
def Fx(a):
    return a.read()

Fx(open('E:\\emp.csv'))

for var in ['f1.csv','f2.csv','f3.csv']:
    r = Fx(var)
    L.append(r)

In [54]:
# map(function,<collection>) -><Generator>
# --------------------------------------------
d={} 
d['CSV'] = list(map(lambda a:a,open('E:\\emp.csv')))
d

{'CSV': ['eid,ename,edept,eplace,ecost\n',
  '101,raj,sales,pune,1000\n',
  '102,leo,prod,bglore,2000\n',
  '103,paul,HR,chennai,3000\n',
  '104,anu,hr,hyderabad,4000\n',
  '456,kumar,sales,bglore,3000\n',
  '105,zion,Hr,mumbai,5000\n',
  '106,bibu,sales,bglore,1450\n',
  '107,theeb,sales,noida,4590\n',
  '108,bibu,sales,bglore,5000\n',
  '113,kumar,prod,hyderabad,5423']}

In [58]:
list(map(lambda a:a>10,[10,20,30,40]))

[False, True, True, True]

In [59]:
L=[]
def f1(a):
    if(a >10):
        return True
    
for var in [10,20,30,40]:
    r = f1(var)
    L.append(r)

print(L)

[None, True, True, True]


In [60]:
print(list(map(lambda a:a>10,[10,20,30,40])) ) # map(function,collection) -><generator>

print('') # empty line

print(list(filter(lambda a:a>10,[10,20,30,40])) ) # filter(function,collection) -><generator>

[False, True, True, True]

[20, 30, 40]


In [63]:
print(list(map(lambda a:a+100,[10,20,30,40])) ) # map(function,collection) -><generator>

print('') # empty line

print(list(filter(lambda a:a+100,[10,20,30,40])) ) # filter(function,collection) -><generator>

[110, 120, 130, 140]

[10, 20, 30, 40]


In [66]:
print(list(filter(lambda a:a,[10,20,30,40,None,0])) ) # filter(function,collection) -><generator>

[10, 20, 30, 40]


In [67]:
print(bool(0),bool(None))

False False


In [70]:
# help(enumerate)
for var in enumerate('abc'):
    print(var)

(0, 'a')
(1, 'b')
(2, 'c')


In [71]:
for var in enumerate('abc',5):
    print(var)

(5, 'a')
(6, 'b')
(7, 'c')


In [72]:
for var in enumerate(open('E:\\emp.csv')):
    print(var)

(0, 'eid,ename,edept,eplace,ecost\n')
(1, '101,raj,sales,pune,1000\n')
(2, '102,leo,prod,bglore,2000\n')
(3, '103,paul,HR,chennai,3000\n')
(4, '104,anu,hr,hyderabad,4000\n')
(5, '456,kumar,sales,bglore,3000\n')
(6, '105,zion,Hr,mumbai,5000\n')
(7, '106,bibu,sales,bglore,1450\n')
(8, '107,theeb,sales,noida,4590\n')
(9, '108,bibu,sales,bglore,5000\n')
(10, '113,kumar,prod,hyderabad,5423')


In [73]:
for var in enumerate(open('E:\\emp.csv'),1):
    print(var)

(1, 'eid,ename,edept,eplace,ecost\n')
(2, '101,raj,sales,pune,1000\n')
(3, '102,leo,prod,bglore,2000\n')
(4, '103,paul,HR,chennai,3000\n')
(5, '104,anu,hr,hyderabad,4000\n')
(6, '456,kumar,sales,bglore,3000\n')
(7, '105,zion,Hr,mumbai,5000\n')
(8, '106,bibu,sales,bglore,1450\n')
(9, '107,theeb,sales,noida,4590\n')
(10, '108,bibu,sales,bglore,5000\n')
(11, '113,kumar,prod,hyderabad,5423')


In [74]:
for var in enumerate(open('E:\\emp.csv'),1):
    print('{} - {}'.format(var[0],var[1].strip()))

1 - eid,ename,edept,eplace,ecost
2 - 101,raj,sales,pune,1000
3 - 102,leo,prod,bglore,2000
4 - 103,paul,HR,chennai,3000
5 - 104,anu,hr,hyderabad,4000
6 - 456,kumar,sales,bglore,3000
7 - 105,zion,Hr,mumbai,5000
8 - 106,bibu,sales,bglore,1450
9 - 107,theeb,sales,noida,4590
10 - 108,bibu,sales,bglore,5000
11 - 113,kumar,prod,hyderabad,5423


In [75]:
for var in enumerate(open('E:\\emp.csv'),1):
    line,data = var # multiple initialization
    print('{} - {}'.format(line,data.strip()))

1 - eid,ename,edept,eplace,ecost
2 - 101,raj,sales,pune,1000
3 - 102,leo,prod,bglore,2000
4 - 103,paul,HR,chennai,3000
5 - 104,anu,hr,hyderabad,4000
6 - 456,kumar,sales,bglore,3000
7 - 105,zion,Hr,mumbai,5000
8 - 106,bibu,sales,bglore,1450
9 - 107,theeb,sales,noida,4590
10 - 108,bibu,sales,bglore,5000
11 - 113,kumar,prod,hyderabad,5423


In [ ]:
map(function,collection) -><Generator>
filter(function,collection) -><Generator>
reduce(function,collection) -> <Single> <== python2.x Vs functools.reduce()
                                                            python3.x

In [77]:
L=[10,20,30,40,50]
t=0
for var in L:
    t=t+var
print(t)

150


In [78]:
import functools
functools.reduce(lambda t,var:t+var,L)

150

In [83]:
s='101,raj,sales,pune,1000'
s.split(',')[-1]

'1000'

In [76]:
fobj = open('E:\\emp.csv')         # map
L = fobj.readlines()
fobj.close()

total = 0
for var in L:
    if('sales' in var):            # filter
        cost = var.split(",")[-1]  # map
        total = total + int(cost)  # reduce
        
print(total)

15040


In [80]:
map(lambda a:a,open('E:\\emp.csv')) # (A)

filter(lambda a:'sales' in a,map(lambda a:a,open('E:\\emp.csv'))) # (B)

map(lambda a:a.split(",")[-1],filter(lambda a:'sales' in a,map(lambda a:a,open('E:\\emp.csv'))))



15040

In [81]:
functools.reduce(lambda a,b:int(a)+int(b),
                 map(lambda a:a.split(",")[-1],
                     filter(lambda a:'sales' in a,
                            map(lambda a:a,open('E:\\emp.csv')))))

15040

In [84]:
class SalaryNotInRangeError(Exception):
    """Exception raised for errors in the input salary.

    Attributes:
        salary -- input salary which caused the error
        message -- explanation of the error
    """

    def __init__(self, salary, message="Salary is not in (5000, 15000) range"):
        self.salary = salary
        self.message = message
        super().__init__(self.message)


salary = int(input("Enter salary amount: "))
if not 5000 < salary < 15000:
    raise SalaryNotInRangeError(salary)

Enter salary amount: 4500


SalaryNotInRangeError: Salary is not in (5000, 15000) range

In [85]:
var=100
print("Display var value:")
print(VAR)

for var in [1,2,3,4,5]:
    print("Test message:"+str(var))

print("End of the line")

Display var value:


NameError: name 'VAR' is not defined

In [86]:
try:
    var=100
    print("Display var value:")
    print(VAR)
except Exception as eobj:
    print(eobj)

for var in [1,2,3,4,5]:
    print("Test message:"+str(var))

print("End of the line")

Display var value:
name 'VAR' is not defined
Test message:1
Test message:2
Test message:3
Test message:4
Test message:5
End of the line


In [87]:
import sys
# exc_info() - 
try:
    var=100
    print("Display var value:")
    print(VAR)
except Exception as eobj:
    print(sys.exc_info())

for var in [1,2,3,4,5]:
    print("Test message:"+str(var))

print("End of the line")

Display var value:
(<class 'NameError'>, NameError("name 'VAR' is not defined"), <traceback object at 0x0000020E54DF1800>)
Test message:1
Test message:2
Test message:3
Test message:4
Test message:5
End of the line


In [93]:
#help(zip)
for var in zip('abc',[0,1,2],[10,11,12,13]):
    print(var)

('a', 0, 10)
('b', 1, 11)
('c', 2, 12)


In [94]:
d={}
for var in zip('abc',[0,1,2],[10,11,12]):
    K1,V1,V2 = var
    d[K1]=V1,V2 # dict of tuple
    
d

{'a': (0, 10), 'b': (1, 11), 'c': (2, 12)}

In [95]:
L = [10,20,30,40]
L+100

TypeError: can only concatenate list (not "int") to list

In [96]:
L.append('D1')
L.append(True)
L

[10, 20, 30, 40, 'D1', True]

In [98]:
import array
#help(array.array)
arr = array.array('i',[10,20,30,40])
arr

array('i', [10, 20, 30, 40])

In [99]:
arr.append(50)
arr.append(60)
arr

array('i', [10, 20, 30, 40, 50, 60])

In [100]:
arr+100

TypeError: can only append array (not "int") to array

In [101]:
arr.append(70.0) # Vs L.append(7.0) ->OK L.append(True) ->OK

TypeError: 'float' object cannot be interpreted as an integer

In [102]:
import numpy
numpy.__version__

'1.24.3'

In [113]:
import os
import re
print(os.__file__)
print(re.__file__)
print(numpy.__file__)

C:\ProgramData\anaconda3\Lib\os.py
C:\ProgramData\anaconda3\Lib\re\__init__.py
C:\ProgramData\anaconda3\Lib\site-packages\numpy\__init__.py


In [104]:
np_arr = numpy.array([10,20,30,40,50])
np_arr+100   Vs arr+100 ->TypeError <-- L+100

array([110, 120, 130, 140, 150])

In [ ]:
numpy ->array ->collection

10 <= Scalar Vs [10,20] <= Vector(1D)

  [[10,20],[30,40]] <== Matrix (2D) ->row x cols
 
  [[[10,20],[30,40],[50,60]]] <== 3D tensor 
    
    slice row cols 
    

In [105]:
import numpy as np
a1 = np.array([10,20,30,40,50])
a1

array([10, 20, 30, 40, 50])

In [109]:
print(a1[0])
print(a1.ndim) 
print(a1.dtype)
print(a1.shape)

10
1
int32
(5,)


In [117]:
a2 = np.array([[10,20,30,40,50]])
print(a2.ndim)
print(a2.dtype)
print(a2.shape) # row,cols  -> (1,5) -> 1row 5cols
print(a2[0])
print(a2[0][0])
print(a2[0][1])
print(a2[0,0]) # same as a2[0][0]
print(a2[0,1]) # same as a2[0][1]

2
int32
(1, 5)
[10 20 30 40 50]
10
20
10
20


In [122]:
a2 =np.array([[1,2,3],[4,5,6]])

print(a2.ndim,a2.shape)

#   0  1   2
#  C1 C2  C3
#-----------
# 1 | 2 | 3   <== record1  0
# ----------
# 4 | 5 | 6   <== record2  1
# ---------
print(a2[0])
print(a2[1])
print(a2[0][0])
print(a2[0,1])

2 (2, 3)
[1 2 3]
[4 5 6]
1
2


In [126]:
np.array([[1,2,3],[4,5,6],[7,8,9],[np.nan,np.nan,np.nan]])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [nan, nan, nan]])

In [128]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
np.array([1,2,3]) ->int32/64
np.array([1,2,3.0]) ->float32/64

np.array([1,np.nan]) ->float 32/64

np.array([1,2.0,np.nan,'data']) ->object

dtype('float64')

In [132]:
np.array([1,2.0,np.nan,'data']).dtype

dtype('<U32')

In [133]:
np.array(['a','b']).dtype

dtype('<U1')

In [ ]:
range(5) ->type <== python3.x Vs  range(5) ->[] <== python 2.x

np.arange(5)

In [138]:
print(type(range(5))) 

for var in range(5): 
    print(var)

<class 'range'>
0
1
2
3
4


In [140]:
for var in range(3,15): # start=3 stop=14(15-1) step=1
    print(var,end=" ")

3 4 5 6 7 8 9 10 11 12 13 14 

In [141]:
for var in range(3,15,2): # start=3 stop=14 step=2
    print(var,end=" ")

3 5 7 9 11 13 

In [134]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [143]:
np.arange(3,15,4)

array([ 3,  7, 11])

In [144]:
np.random.rand(5)

array([0.60896652, 0.50949269, 0.61877785, 0.35017075, 0.55546644])

In [179]:
arr = np.random.rand()
print(arr)

0.40579749079004057


In [182]:
print(np.array([1,2,3]).ndim)
print(np.array([[1,2,3]]).ndim)
print(np.array([[1,2,3]]).shape) # 2D ->(row,col)
print(np.array([[[1,2,3]]]).ndim)

print(np.array([[[1,2,3]]]).shape) # 3D ->(slice,row,Col)

1
2
(1, 3)
3
(1, 1, 3)


In [183]:
arr = np.array([10,20,30,40])
arr+100

array([110, 120, 130, 140])

In [184]:
arr*0.12

array([1.2, 2.4, 3.6, 4.8])

In [190]:
arr=np.arange(15)
print(arr[2:8] )
print(arr[:8])
print(arr[4:]) # 4th index to list of all

[2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[ 4  5  6  7  8  9 10 11 12 13 14]


In [191]:
np.sum(arr)

105

In [192]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) 
print(arr.ndim)
print(arr.shape)
print(arr[1, 1:3]) 

2
(2, 5)
[7 8]


In [193]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr.shape

(3, 4)

In [195]:
np.reshape(arr,(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [196]:
np.reshape(arr,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [198]:
a1 = np.arange(1,10)
a2 = np.arange(11,20)
a1+a2

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [199]:
a1/a2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [200]:
np.divide(a1,a2)

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [205]:
print(a1 >5 )
print('')
print(a1 <a2)
print('')
print(np.less(a1,a2)) # same as a1 < a2 

[False False False False False  True  True  True  True]

[ True  True  True  True  True  True  True  True  True]

[ True  True  True  True  True  True  True  True  True]


In [206]:
np.sin(30)

-0.9880316240928618

In [207]:
import pandas
pandas.__version__

'2.0.3'

In [208]:
pandas.__file__

'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'

In [210]:
print(pandas.Series)
print(pandas.DataFrame)

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [211]:
pandas.Series({'K1':[10,20,30]})

K1    [10, 20, 30]
dtype: object

In [212]:
pandas.DataFrame({'K1':[10,20,30]})

K1
0  10
1  20
2  30

In [213]:
import pandas as pd
pd.DataFrame({'K1':[10,20,30,40],'K2':[100,200,300,400]})

K1   K2
0  10  100
1  20  200
2  30  300
3  40  400

In [214]:
df = pd.DataFrame({'K1':[10,20,30,40],'K2':[100,200,300,400]})
df['K1'] # like dict -> dictname['Key'] ->Value

0    10
1    20
2    30
3    40
Name: K1, dtype: int64

In [215]:
df.loc[3] # index based (or) record based

K1     40
K2    400
Name: 3, dtype: int64

In [216]:
df.loc[3]['K1'] # 3rd row K1 cols

40

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   K1      4 non-null      int64
 1   K2      4 non-null      int64
dtypes: int64(2)
memory usage: 196.0 bytes


In [219]:
df.iloc[3]['K2']

400

In [220]:
df.shape # like numpy shape

(4, 2)

In [228]:
df = pd.DataFrame({'K1':[10,20,30,40],'K2':[100,200,300,400]})
print(df.index)
print(df.columns)
df.loc[1]

RangeIndex(start=0, stop=4, step=1)
Index(['K1', 'K2'], dtype='object')


K1     20
K2    200
Name: 1, dtype: int64

In [224]:
df.loc[1]['K2']

200

In [227]:
for var in df.index:
    print(df.loc[var]['K2'])

100
200
300
400


In [230]:
pd.read_csv('E:\\emp.csv')

eid  ename  edept     eplace  ecost
0  101    raj  sales       pune   1000
1  102    leo   prod     bglore   2000
2  103   paul     HR    chennai   3000
3  104    anu     hr  hyderabad   4000
4  456  kumar  sales     bglore   3000
5  105   zion     Hr     mumbai   5000
6  106   bibu  sales     bglore   1450
7  107  theeb  sales      noida   4590
8  108   bibu  sales     bglore   5000
9  113  kumar   prod  hyderabad   5423

In [231]:
df = pd.read_csv('E:\\emp.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   eid     10 non-null     int64 
 1   ename   10 non-null     object
 2   edept   10 non-null     object
 3   eplace  10 non-null     object
 4   ecost   10 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes


In [232]:
df.shape

(10, 5)

In [233]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [234]:
df.columns

Index(['eid', 'ename', 'edept', 'eplace', 'ecost'], dtype='object')

In [235]:
df.loc[3]

eid             104
ename           anu
edept            hr
eplace    hyderabad
ecost          4000
Name: 3, dtype: object

In [236]:
df.loc[1:5] # from 1st index to 5th index 

eid  ename  edept     eplace  ecost
1  102    leo   prod     bglore   2000
2  103   paul     HR    chennai   3000
3  104    anu     hr  hyderabad   4000
4  456  kumar  sales     bglore   3000
5  105   zion     Hr     mumbai   5000

In [237]:
df.loc[1:5]['ename']

1      leo
2     paul
3      anu
4    kumar
5     zion
Name: ename, dtype: object

In [245]:
df.loc[1:5][['ename','edept']]

ename  edept
1    leo   prod
2   paul     HR
3    anu     hr
4  kumar  sales
5   zion     Hr

In [244]:
L=[]
L.append("D1")
L.append(["D2","D3"])

In [246]:
df1 = pd.DataFrame({'K1':[10,20,30],'K2':[100,200,300]},index=['A','B','C'])
df1

K1   K2
A  10  100
B  20  200
C  30  300

In [247]:
df

eid  ename  edept     eplace  ecost
0  101    raj  sales       pune   1000
1  102    leo   prod     bglore   2000
2  103   paul     HR    chennai   3000
3  104    anu     hr  hyderabad   4000
4  456  kumar  sales     bglore   3000
5  105   zion     Hr     mumbai   5000
6  106   bibu  sales     bglore   1450
7  107  theeb  sales      noida   4590
8  108   bibu  sales     bglore   5000
9  113  kumar   prod  hyderabad   5423

In [249]:
pd.read_csv('E:\\emp.csv',index_col=2)

eid  ename     eplace  ecost
edept                              
sales  101    raj       pune   1000
prod   102    leo     bglore   2000
HR     103   paul    chennai   3000
hr     104    anu  hyderabad   4000
sales  456  kumar     bglore   3000
Hr     105   zion     mumbai   5000
sales  106   bibu     bglore   1450
sales  107  theeb      noida   4590
sales  108   bibu     bglore   5000
prod   113  kumar  hyderabad   5423

In [250]:
df2 = pd.read_csv('E:\\emp.csv',index_col=2)
df2.index

Index(['sales', 'prod', 'HR', 'hr', 'sales', 'Hr', 'sales', 'sales', 'sales',
       'prod'],
      dtype='object', name='edept')

In [252]:
df2.loc['sales']

eid  ename  eplace  ecost
edept                           
sales  101    raj    pune   1000
sales  456  kumar  bglore   3000
sales  106   bibu  bglore   1450
sales  107  theeb   noida   4590
sales  108   bibu  bglore   5000

In [254]:
df2.iloc[2:5]

eid  ename     eplace  ecost
edept                              
HR     103   paul    chennai   3000
hr     104    anu  hyderabad   4000
sales  456  kumar     bglore   3000

In [255]:
df2.iloc[2:5][['eid','ename','eplace']]

eid  ename     eplace
edept                       
HR     103   paul    chennai
hr     104    anu  hyderabad
sales  456  kumar     bglore

In [276]:
df2['ecost'] >3000

edept
sales    False
prod     False
HR       False
hr        True
sales    False
Hr        True
sales    False
sales     True
sales     True
prod      True
Name: ecost, dtype: bool

In [285]:
df2['ecost']

edept
sales    1000
prod     2000
HR       3000
hr       4000
sales    3000
Hr       5000
sales    1450
sales    4590
sales    5000
prod     5423
Name: ecost, dtype: int64

In [258]:
df2[df2['ecost'] >3000]

eid  ename     eplace  ecost
edept                              
hr     104    anu  hyderabad   4000
Hr     105   zion     mumbai   5000
sales  107  theeb      noida   4590
sales  108   bibu     bglore   5000
prod   113  kumar  hyderabad   5423

In [286]:
df2[df2['ecost'] >3000][['ename','eplace']]

ename     eplace
edept                  
hr       anu  hyderabad
Hr      zion     mumbai
sales  theeb      noida
sales   bibu     bglore
prod   kumar  hyderabad

In [282]:
df2['ecost'] >3000 
df2['ecost'] <5000

edept
sales     True
prod      True
HR        True
hr        True
sales     True
Hr       False
sales     True
sales     True
sales    False
prod     False
Name: ecost, dtype: bool

In [263]:
df2.loc['sales']
df2.loc['sales']['ename'] == 'raj'

edept
sales     True
sales    False
sales    False
sales    False
sales    False
Name: ename, dtype: bool

In [283]:
df2.loc['sales']['ename'] == 'raj'

edept
sales     True
sales    False
sales    False
sales    False
sales    False
Name: ename, dtype: bool

In [284]:
df2.loc['sales'][df2.loc['sales']['ename'] == 'raj']

eid ename eplace  ecost
edept                         
sales  101   raj   pune   1000

In [287]:
df2.duplicated()

edept
sales    False
prod     False
HR       False
hr       False
sales    False
Hr       False
sales    False
sales    False
sales    False
prod     False
dtype: bool

In [288]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, sales to prod
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   eid     10 non-null     int64 
 1   ename   10 non-null     object
 2   eplace  10 non-null     object
 3   ecost   10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 700.0+ bytes


In [289]:
df2.drop_duplicates()

eid  ename     eplace  ecost
edept                              
sales  101    raj       pune   1000
prod   102    leo     bglore   2000
HR     103   paul    chennai   3000
hr     104    anu  hyderabad   4000
sales  456  kumar     bglore   3000
Hr     105   zion     mumbai   5000
sales  106   bibu     bglore   1450
sales  107  theeb      noida   4590
sales  108   bibu     bglore   5000
prod   113  kumar  hyderabad   5423

In [293]:
d={'K1':[np.nan,np.nan,np.nan],'K2':[10,None,np.nan]}
d

{'K1': [nan, nan, nan], 'K2': [10, None, nan]}

In [294]:
df3 = pd.DataFrame(d)
print(df3)

   K1    K2
0 NaN  10.0
1 NaN   NaN
2 NaN   NaN


In [295]:
df3.isnull()

K1     K2
0  True  False
1  True   True
2  True   True

In [296]:
df3.isnull().sum()

K1    3
K2    2
dtype: int64

In [297]:
df2.isnull().sum() 

eid       0
ename     0
eplace    0
ecost     0
dtype: int64

In [298]:
df3.fillna(value=50) # replace NaN value

K1    K2
0  50.0  10.0
1  50.0  50.0
2  50.0  50.0

In [299]:
df3

K1    K2
0 NaN  10.0
1 NaN   NaN
2 NaN   NaN

In [300]:
df3.fillna(value=50,inplace=True)

In [301]:
df3

K1    K2
0  50.0  10.0
1  50.0  50.0
2  50.0  50.0

In [302]:
d={'K1':[np.nan,np.nan,np.nan],'K2':[10,None,np.nan]}
df4 = pd.DataFrame(d)
df4.isnull().sum()

K1    3
K2    2
dtype: int64

In [303]:
df4

K1    K2
0 NaN  10.0
1 NaN   NaN
2 NaN   NaN

In [308]:
df4['K1'].fillna(value=50)  # Vs df4.fillna(value=50)

0    50.0
1    50.0
2    50.0
Name: K1, dtype: float64

In [309]:
df4

K1    K2
0 NaN  10.0
1 NaN   NaN
2 NaN   NaN

In [310]:
df4['K1'].fillna(value=50,inplace=True)

In [311]:
df4

K1    K2
0  50.0  10.0
1  50.0   NaN
2  50.0   NaN

In [312]:
df4.isnull().sum()

K1    0
K2    2
dtype: int64